#!/usr/bin/env python3
import rospy
from geometry_msgs.msg
import Twist
def move_square():

rospy.init_node('square_drive',
anonymous=True)
 pub =
rospy.Publisher('/cmd_vel',
Twist, queue_size=10)
 rate = rospy.Rate(10)
 fwd = Twist()
 fwd.linear.x = 0.2
 turn = Twist()
 turn.angular.z = -0.4
 for i in range(4):
 rospy.loginfo(f"Side {i+1}")
 for _ in range(30):
 pub.publish(fwd)
 rate.sleep()
 rospy.sleep(1)
 rospy.loginfo("Turning")
 for _ in range(20):
 pub.publish(turn)
 rate.sleep()
 rospy.sleep(1)
 stop = Twist()
 pub.publish(stop)
 rospy.loginfo("Square
complete!")
if __name__ == '__main__':
 try:
 move_square()
 except
rospy.ROSInterruptException:
 pass
